name: Messenger

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Выбор репозитория
        uses: actions/checkout@v3

      - name: Установка Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt

      - name: Проверка кода с flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Тесты с Pytest
        run: |
          python -m pytest tests
